In [195]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
!pip install pandas_datareader
from pandas_datareader import data as pdr
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: pandas_datareader in c:\users\sdmlab\anaconda3\lib\site-packages (0.9.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\sdmlab\anaconda3\lib\site-packages (from pandas_datareader) (2.25.1)
Requirement already satisfied: lxml in c:\users\sdmlab\anaconda3\lib\site-packages (from pandas_datareader) (4.6.3)
Requirement already satisfied: pandas>=0.23 in c:\users\sdmlab\anaconda3\lib\site-packages (from pandas_datareader) (1.2.4)
Requirement already satisfied: numpy>=1.16.5 in c:\users\sdmlab\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\sdmlab\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\sdmlab\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\sdmlab\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas_datareader) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sdmlab\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sdmlab\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\sdmlab\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sdmlab\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.10)

In [196]:
ticker = pd.read_excel("ticker.xlsx")
remove = pd.read_excel("removed.xlsx")
added = pd.read_excel("added.xlsx")
add = list(added["Added"])
gone = list(remove["Removed"])
ticker = list(ticker["Symbol"])

In [197]:
#ticker filter based on survival
for i in add:
    if i in ticker:
        ticker.remove(i)

In [198]:
for i in gone:
    if i in ticker:
        ticker.remove(i)
        
len(ticker)

213

In [199]:
start = dt.datetime(2000,1,1)
end = dt.datetime(2019,12,31)
start, end
tick = ticker
len(tick)

213

In [200]:
p = 0
delet_tick =[]
for i in ticker:
    try:
        stocks = pdr.get_data_yahoo(i, start, end)
        stocks = stocks["Adj Close"]
        stocks.to_csv(str(i)+".csv")

        print(i)
        p = p +1
        print(p)
    except:
        print('{} is deleted'.format(i))
        delet_tick.append(i)

ED
1
GLW
2
DHR
3
DRI
4
D
5
ETN
6
ES
7
FITB
8
FE
9
BEN
10
FCX
11
GE
12
HUM
13
HBAN
14
KLAC
15
LEG
16
L
17
MAR
18
MKC
19
MCK
20
MET
21
MCO
22
MS
23
MSI
24
NI
25
NTRS
26
OMC
27
PAYX
28
PNW
29
PPL
30
QCOM
31
RTX
32
ROK
33
SPGI
34
SRE
35
SBUX
36
STT
37
TROW
38
TPR
39
TXN
40
TSN
41
USB
42
VLO
43
VIAC
44
VNO
45
WM
46
WAT
47
WRK
48
WY
49
WHR
50
MO
51
AEP
52
BA
53
BMY
54
CPB
55
CAT
56
CVX
57
KO
58
CL
59
COP
60
CVS
61
DE
62
DTE
63
EIX
64
ETR
65
EXC
66
XOM
67
F
68
GD
69
HAL
70
HIG
71
HSY
72
IBM
73
IP
74
KMB
75
KR
76
MRK
77
NSC
78
PEP
79
PFE
80
PPG
81
PG
82
PEG
83
SEE
84
SO
85
UNP
86
XEL
87
ABT
88
HON
89
HWM
90
SHW
91
CMI
92
EMR
93
SLB
94
CSX
95
CLX
96
GIS
97
NEM
98
MCD
99
LLY
100
BAX
101
BDX
102
JNJ
103
GPC
104
HPQ
105
WMB
106
JPM
107
IFF
108
AXP
109
BAC
110
CI
111
DUK
112
LNC
113
TAP
114
NEE
115
DIS
116
WFC
117
MMM
118
INTC
119
TGT
120
TXT
121
VFC
122
WBA
123
AIG
124
FDX
125
PCAR
126
ADP
127
GWW
128
MAS
129
ADM
130
WMT
131
SNA
132
SWK
133
BF.B is deleted
AAPL
134
OXY
135
CAG
136
LB
137
T
138
VZ
139
LOW
140
PHM
141
HES
142
LMT
143
HAS
144
BLL
145
APD
146
NUE
147
PKI
148
NOC
149
CNP
150
TJX
151
DOV
152
PH
153
ITW
154
GPS
155
MDT
156
SYY
157
MMC
158
AVY
159
HD
160
PNC
161
C
162
NKE
163
ECL
164
GL
165
NWL
166
ORCL
167
K
168
ADSK
169
MRO
170
AEE
171
AMGN
172
LIN
173
IPG
174
COST
175
CSCO
176
EMN
177
KEY
178
UNM
179
MSFT
180
LUV
181
UNH
182
MU
183
BSX
184
AMAT
185
BK
186
ALL
187
CMA
188
AON
189
AZO
190
ADBE
191
CAH
192
SCHW
193
EFX
194
APA
195
PGR
196
YUM
197
TFC
198
CINF
199
COF
200
RF
201
AES
202
CCL
203
LUMN is deleted
CMS
204
AFL
205
NTAP
206
BBY
207
VMC
208
ADI
209
XLNX
210
CTXS
211

In [201]:
delet_tick

['BF.B', 'LUMN']

In [234]:
stocks = pd.read_csv("GLW.csv")
for i in tick:
    try:
        if i != "GLW":
            temp = pd.read_csv(str(i)+".csv")
            stocks[str(i)] = temp["Adj Close"]
    except:
        print("yikes: " + str(i))

yikes: BF.B

In [235]:
stocks.rename(columns = {"Adj Close":"GLW"},inplace =True)

In [243]:
bond = pd.read_csv("^TNX.csv")
stocks["Bond"] =  bond["Adj Close"]
stocks

,Date,GLW,ED,DHR,DRI,D,ETN,ES,FITB,FE,...,LUMN,CMS,AFL,NTAP,BBY,VMC,ADI,XLNX,CTXS,Bond
0,1999-12-31,31.811966,12.533850,8.598002,6.842910,8.140931,7.445930,10.393553,27.629105,8.556245,...,15.139324,16.080086,7.797564,34.266247,15.205649,28.561920,30.839806,32.169292,47.334377,6.435
1,2000-01-03,30.054056,12.261371,8.286164,6.536156,7.907593,7.317771,10.456738,26.311176,8.320537,...,14.460250,15.210019,7.394774,35.065536,17.475147,28.159639,29.907148,33.075779,49.306641,6.548
2,2000-01-04,27.139629,12.420315,7.985457,6.488966,8.102039,7.067861,10.456738,25.205080,8.320537,...,13.881040,15.403369,7.198545,30.630770,17.361671,28.070229,28.394154,32.324043,46.877384,6.485
3,2000-01-05,26.522818,12.987975,8.074558,6.724930,8.322412,7.125534,10.519917,24.828533,8.626957,...,13.980909,15.822284,7.157234,32.332481,17.248194,29.947557,28.808693,31.616535,44.183556,6.599
4,2000-01-06,25.906012,13.010677,8.163657,6.654139,8.413158,7.272914,10.646287,25.699299,8.650528,...,13.821123,15.693391,7.301818,28.903280,17.096903,29.992252,28.021109,28.874968,40.407387,6.549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5027,2019-12-24,27.611948,84.514107,152.390671,106.368378,76.701988,91.370293,80.553131,28.920567,45.361813,...,11.586657,59.788013,50.674458,59.461231,84.571785,140.488144,116.309135,97.003059,108.825691,NaN
5028,2019-12-26,27.813147,84.495262,152.042465,106.770332,76.796257,91.911858,80.879341,29.070028,45.389889,...,11.542635,59.788013,50.539993,59.139622,84.494835,141.472977,116.318855,97.190186,109.405869,NaN
5029,2019-12-27,27.583208,84.768593,152.102158,105.888016,77.305344,91.863503,80.898521,28.864519,45.277607,...,11.815574,60.037613,50.539993,58.108555,83.686928,141.709366,116.046837,96.934113,108.943687,NaN
5030,2019-12-30,27.793985,85.004219,152.062332,106.819351,77.380775,91.805481,80.984871,28.760962,45.371174,...,11.533833,60.085609,50.655247,58.203148,84.225533,140.369980,115.473640,96.205284,108.520866,NaN
5031,2019-12-31,27.889795,85.268112,152.699097,106.868370,78.078400,91.602386,81.618095,28.939837,45.474091,...,11.630680,60.325607,50.808918,58.884216,84.446754,141.807846,115.454208,96.293915,109.051865,NaN

In [244]:
stocks["Bond"].fillna(method = "pad",inplace = True)

In [252]:
stocks.set_index("Date",inplace = True)

In [253]:
stocks["Bond"].isnull().sum()

0

In [260]:
stockret = np.log(stocks/stocks.shift(1))
stockret.iloc[0:1,0:214] = 0.0
stockret

,GLW,ED,DHR,DRI,D,ETN,ES,FITB,FE,BEN,...,LUMN,CMS,AFL,NTAP,BBY,VMC,ADI,XLNX,CTXS,Bond
Date,,,,,,,,,,,,,,,,,,,,,
1999-12-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2000-01-03,-0.056845,-0.021979,-0.036943,-0.045864,-0.029081,-0.017362,0.006061,-0.048876,-0.027935,-0.011765,...,-0.045892,-0.055627,-0.053038,0.023058,0.139113,-0.014185,-0.030709,0.027789,0.040822,0.017408
2000-01-04,-0.102003,0.012880,-0.036965,-0.007246,0.024292,-0.034748,0.000000,-0.042948,0.000000,-0.017911,...,-0.040880,0.012632,-0.026895,-0.135214,-0.006515,-0.003180,-0.051914,-0.022990,-0.050523,-0.009668
2000-01-05,-0.022990,0.044691,0.011096,0.035718,0.026836,0.008127,0.006024,-0.015052,0.036165,0.015937,...,0.007169,0.026833,-0.005755,0.054067,-0.006558,0.064738,0.014494,-0.022131,-0.059183,0.017426
2000-01-06,-0.023530,0.001746,0.010974,-0.010582,0.010845,0.020472,0.011941,0.034470,0.002729,0.059462,...,-0.011495,-0.008180,0.020000,-0.112117,-0.008810,0.001491,-0.027719,-0.090705,-0.089340,-0.007606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-24,-0.010356,-0.001226,0.000652,-0.001842,-0.000860,-0.006856,0.002743,0.000323,0.001858,-0.001911,...,-0.002277,-0.000161,0.004179,0.000955,0.003304,0.016183,0.004605,-0.004154,0.004619,0.000000
2019-12-26,0.007260,-0.000223,-0.002288,0.003772,0.001228,0.005910,0.004041,0.005155,0.000619,0.006862,...,-0.003807,0.000000,-0.002657,-0.005423,-0.000910,0.006986,0.000084,0.001927,0.005317,0.000000
2019-12-27,-0.008302,0.003230,0.000393,-0.008298,0.006607,-0.000526,0.000237,-0.007095,-0.002477,-0.002663,...,0.023371,0.004166,0.000000,-0.017588,-0.009608,0.001670,-0.002341,-0.002638,-0.004233,0.000000
2019-12-30,0.007612,0.002776,-0.000262,0.008757,0.000975,-0.000632,0.001067,-0.003594,0.002064,-0.006178,...,-0.024134,0.000799,0.002278,0.001627,0.006415,-0.009497,-0.004952,-0.007547,-0.003889,0.000000
2019-12-31,0.003441,0.003100,0.004179,0.000459,0.008975,-0.002215,0.007789,0.006200,0.002266,0.006178,...,0.008362,0.003986,0.003029,0.011634,0.002623,0.010191,-0.000168,0.000921,0.004881,0.000000

In [267]:
tradDays = []
dfs= []
for i in range(2000,2020):
    dfs.append(stockret.loc[str(i)+"-01-01":str(i)+"-12-31"])
    tradDays.append(len(stockret.loc[str(i)+"-01-01":str(i)+"-12-31"]))

In [272]:
tradDays

[252,
 248,
 252,
 252,
 252,
 252,
 251,
 251,
 253,
 252,
 252,
 252,
 250,
 252,
 252,
 252,
 252,
 251,
 251,
 252]

In [255]:
logretar = np.full((253*6,5),np.random.uniform(-1,1,(253*6,5))+1)

In [257]:
logret = pd.DataFrame(logretar)
logret = stockret
logret.shape

(5032, 213)

          a         b         c         d      bond
0  1.797682  0.348569  0.349211  0.742229  0.274271
1  1.653388  0.560839  1.141795  0.006185  0.771860
2  0.169652  0.763793  0.101076  0.203491  1.824384

In [273]:
year = 6
assets = 5
cumDays = []
for i in range(len(tradDays)):
    if i==0:
        cumDays.append(tradDays[i])
    else:
        cumDays.append(tradDays[i]+cumDays[i-1])
        
print(cumDays)

[252, 500, 752, 1004, 1256, 1508, 1759, 2010, 2263, 2515, 2767, 3019, 3269, 3521, 3773, 4025, 4277, 4528, 4779, 5031]

            a         b         c         d      bond
0    1.797682  0.348569  0.349211  0.742229  0.274271
1    1.653388  0.560839  1.141795  0.006185  0.771860
2    0.169652  0.763793  0.101076  0.203491  1.824384
3    0.477447  0.093008  1.653365  1.233229  1.215868
4    0.596086  0.957864  0.203729  0.730013  0.157340
..        ...       ...       ...       ...       ...
248  0.788109  0.128586  0.185148  0.209424  1.277756
249  1.178840  0.914741  0.380204  1.091103  1.511626
250  1.679995  0.582179  1.399725  1.660975  0.449432
251  1.898074  0.292143  1.272439  0.108412  0.157411
252  0.402372  1.875837  0.052041  1.906783  1.917861

[253 rows x 5 columns]

In [278]:
stockret

,GLW,ED,DHR,DRI,D,ETN,ES,FITB,FE,BEN,...,LUMN,CMS,AFL,NTAP,BBY,VMC,ADI,XLNX,CTXS,Bond
Date,,,,,,,,,,,,,,,,,,,,,
1999-12-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2000-01-03,-0.056845,-0.021979,-0.036943,-0.045864,-0.029081,-0.017362,0.006061,-0.048876,-0.027935,-0.011765,...,-0.045892,-0.055627,-0.053038,0.023058,0.139113,-0.014185,-0.030709,0.027789,0.040822,0.017408
2000-01-04,-0.102003,0.012880,-0.036965,-0.007246,0.024292,-0.034748,0.000000,-0.042948,0.000000,-0.017911,...,-0.040880,0.012632,-0.026895,-0.135214,-0.006515,-0.003180,-0.051914,-0.022990,-0.050523,-0.009668
2000-01-05,-0.022990,0.044691,0.011096,0.035718,0.026836,0.008127,0.006024,-0.015052,0.036165,0.015937,...,0.007169,0.026833,-0.005755,0.054067,-0.006558,0.064738,0.014494,-0.022131,-0.059183,0.017426
2000-01-06,-0.023530,0.001746,0.010974,-0.010582,0.010845,0.020472,0.011941,0.034470,0.002729,0.059462,...,-0.011495,-0.008180,0.020000,-0.112117,-0.008810,0.001491,-0.027719,-0.090705,-0.089340,-0.007606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-24,-0.010356,-0.001226,0.000652,-0.001842,-0.000860,-0.006856,0.002743,0.000323,0.001858,-0.001911,...,-0.002277,-0.000161,0.004179,0.000955,0.003304,0.016183,0.004605,-0.004154,0.004619,0.000000
2019-12-26,0.007260,-0.000223,-0.002288,0.003772,0.001228,0.005910,0.004041,0.005155,0.000619,0.006862,...,-0.003807,0.000000,-0.002657,-0.005423,-0.000910,0.006986,0.000084,0.001927,0.005317,0.000000
2019-12-27,-0.008302,0.003230,0.000393,-0.008298,0.006607,-0.000526,0.000237,-0.007095,-0.002477,-0.002663,...,0.023371,0.004166,0.000000,-0.017588,-0.009608,0.001670,-0.002341,-0.002638,-0.004233,0.000000
2019-12-30,0.007612,0.002776,-0.000262,0.008757,0.000975,-0.000632,0.001067,-0.003594,0.002064,-0.006178,...,-0.024134,0.000799,0.002278,0.001627,0.006415,-0.009497,-0.004952,-0.007547,-0.003889,0.000000
2019-12-31,0.003441,0.003100,0.004179,0.000459,0.008975,-0.002215,0.007789,0.006200,0.002266,0.006178,...,0.008362,0.003986,0.003029,0.011634,0.002623,0.010191,-0.000168,0.000921,0.004881,0.000000

In [298]:
testYears = 3
annGrowth = 1.048

In [299]:
totGrowth = annGrowth**testYears
totGrowth

1.1510225920000001

In [315]:
def Mu(df,tradDays):
    mu  = df.mean()*tradDays
    
    mu.values.T
    return mu

def Sigma(df,tradDays):
    sigma = df.cov()*tradDays
    
    sigma = sigma.values
    return sigma

In [352]:
def Delta(df):
    delta = np.full((len(df.columns),1),0.02)
    delta[len(df.columns)-1] = 0.005
    return delta

In [353]:
Delta(dfs[1])

array([[0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.005]])

In [40]:
import cvxpy as cp

In [354]:
train =stockret.loc["2000-01-01":"2016-12-31"]
val = stockret.loc["2017-01-01":"2018-12-31"]
test = stockret.loc["2019-01-01":"2019-06-31"]

In [367]:
def optimize(train,tradDays,x = 1,lambda0 = 1,give = "w"):
    w = cp.Variable(len(train.columns))
    w_plus = cp.Variable(len(train.columns))
    w_minus = cp.Variable(len(train.columns))
    delta = x*Delta(train).reshape(len(train.columns),1)

    ret = Mu(train,tradDays).to_numpy().T*w
    aux = delta.T*(w_plus + w_minus)
    risk = cp.quad_form(w,Sigma(train,tradDays))

    prob = cp.Problem(
        cp.Minimize(risk-lambda0*ret + lambda0*aux),
        [sum(w) ==1,
        w == w_plus - w_minus,
        w_plus>=0,
        w_minus>=0,
        w>=0])

    prob.solve()
    param = []
    param.append(w.value)
    param.append(Mu(train,tradDays).dot(w.value))
    param.append(np.sqrt(w.value.dot(Sigma(train,tradDays)).dot(w.value)))
    
    if give == "w":
        return w.value
    elif give == "return":
        return Mu(train,tradDays).dot(w.value)
    elif give == "std":
        param.append(Mu(train,tradDays).dot(w.value))
        return np.sqrt(w.value.dot(Sigma(train,tradDays)).dot(w.value))
    elif give == "list":
        return param

In [363]:
optimize(train,251,give="list")[1]

0.19950992661361994

In [373]:
for i in np.arange(10,30,1):
    
    t = optimize(train,251,i,1,"list")
    print(str(i)+" "+str(t[1])+" "+str(t[2]))

10 0.1993515697952901 0.17210290577729134
11 0.19935156979529012 0.17210290577729143
12 0.19935156979529006 0.17210290577729132
13 0.19929739882422282 0.17209799272772716
14 0.1918646038682974 0.16858537954848118
15 0.17577616593713502 0.16181540421163337
16 0.15993471564647488 0.15782496262664508
17 0.1435754873610297 0.15680246639821885
18 0.12768980009008804 0.1588326933208253
19 0.11164044810250713 0.16378193320754159
20 0.09522540808597071 0.17118509501917273
21 0.07963131461210492 0.18064391685487247
22 0.06363254567315299 0.1913840327131437
23 0.04829948076242676 0.20356309107042753
24 0.03300019274241629 0.2167916346858538
25 0.01807267936159163 0.23002853045136165
26 0.003313825793216518 0.24430163688601922
27 -0.01167845364735623 0.25939733267611287
28 -0.026585890461351635 0.27521869693267886
29 -0.04105195070135662 0.29143152377405873

In [383]:
for i in np.arange(0,0.1,0.01):
    
    t = optimize(train,251,1,i,"list")
    print(str(i)+" "+str(t[1])+" "+str(t[2]))

0.0 0.07031952528590077 0.09584932595128502
0.01 0.07648280464447266 0.09605324715766747
0.02 0.0847722389100986 0.09669207103240116
0.03 0.09257512241409303 0.09768623328383914
0.04 0.09974726327648782 0.09894265631959212
0.05 0.10646816251105937 0.10043599331687025
0.06 0.11275088469141815 0.10211413698769997
0.07 0.11896457547952244 0.10404194922708257
0.08 0.12441757819224604 0.1059487567217597
0.09 0.12947047334927456 0.10791313737827023

In [377]:
np.arange(-1,1,0.2)

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

# CAPM

In [385]:
ticker = pd.read_excel("ticker.xlsx")
remove = pd.read_excel("gone1.xlsx")
added = pd.read_excel("gone1.xlsx")
add1 = list(added["Added"])
gone1 = list(remove["Removed"])
ticker1 = list(ticker["Symbol"])